// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmnn-rt3_ooaP2IhZUal4VZ-sp0y3ysHA',
    appId: '1:1035040052385:web:59a80f88e7a6e3cb75cce0',
    messagingSenderId: '1035040052385',
    projectId: 'todo-app-bb2ab',
    authDomain: 'todo-app-bb2ab.firebaseapp.com',
    storageBucket: 'todo-app-bb2ab.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFz2FKlQEakS6S_keaOJqOEWGJYDl7KJY',
    appId: '1:1035040052385:android:1be368d917eac50d75cce0',
    messagingSenderId: '1035040052385',
    projectId: 'todo-app-bb2ab',
    storageBucket: 'todo-app-bb2ab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBdu-pzQ4T_4ZCtgFP4Hq3_AHwFtDV-CA',
    appId: '1:1035040052385:ios:03be19b97082c40475cce0',
    messagingSenderId: '1035040052385',
    projectId: 'todo-app-bb2ab',
    storageBucket: 'todo-app-bb2ab.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBdu-pzQ4T_4ZCtgFP4Hq3_AHwFtDV-CA',
    appId: '1:1035040052385:ios:03be19b97082c40475cce0',
    messagingSenderId: '1035040052385',
    projectId: 'todo-app-bb2ab',
    storageBucket: 'todo-app-bb2ab.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmnn-rt3_ooaP2IhZUal4VZ-sp0y3ysHA',
    appId: '1:1035040052385:web:c064e415fbbcabf075cce0',
    messagingSenderId: '1035040052385',
    projectId: 'todo-app-bb2ab',
    authDomain: 'todo-app-bb2ab.firebaseapp.com',
    storageBucket: 'todo-app-bb2ab.firebasestorage.app',
  );
}
